version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

  settings:
    govet:
      enable:
        - shadow

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - errcheck
